# Makefile option setting
# for Intel Fortran compiler
# FC = mpif90
# FFLAGS = -O3
# FFLAGS = -CB -traceback -O0 -fpe0 -g -check # debug mode

# for Intel Fortran compiler on MIC
# FC = mpif90
# FFLAGS = -O3 -mmic

# for Gfortran
# FC = gfortran
# FFLAGS = -O3 -funroll-loops -msse3 -m64 

# for FX10 fujitsu compiler
FC = mpifrtpx
FFLAGS = -O3 -Kfast # pure MPI processing
#FFLAGS = -O3 -Kfast -Kopenmp # MPI/OpenMP hybird