partition:
	../../ppohFEM/bin/ppohFEM_part 
run:
	mpirun -np 4 ../bin/app_struct
clean:
	rm -f A300_vis_psf.0001.inp hecmw_part.log part.inp 0.log 1.log 2.log 3.log struct.dbg.0 struct.dbg.1 struct.dbg.2 struct.dbg.3 struct.msg struct.sta
