//============================================================
//=== OAT_Routines Header
//============================================================
int OAT_InstallMyMatMul(int n,double A[N][N],double C[N][N],double B[N][N],int iusw1);
int OAT_InstallMyMatMul_1(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_2(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_3(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_4(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_5(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_6(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_7(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_8(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_9(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_10(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_11(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_12(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_13(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_14(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_15(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_16(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_17(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_18(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_19(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_20(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_21(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_22(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_23(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_24(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_25(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_26(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_27(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_28(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_29(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_30(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_31(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_32(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_33(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_34(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_35(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_36(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_37(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_38(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_39(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_40(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_41(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_42(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_43(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_44(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_45(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_46(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_47(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_48(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_49(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_50(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_51(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_52(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_53(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_54(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_55(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_56(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_57(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_58(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_59(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_60(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_61(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_62(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_63(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_InstallMyMatMul_64(int n,double A[N][N],double C[N][N],double B[N][N]);
int OAT_ATset(int OAT_TYPE, char *OAT_Routines);
int OAT_SetParm(int OAT_TYPE,char *OAT_Routines,int n_bpset,int *isw);
int OAT_ATexec(int OAT_TYPE,char *OAT_Routines,int n,double A[N][N],double B[N][N],double C[N][N]);
int OAT_ATexecInstallMyMatMul(char *OAT_Routines,int n,double A[N][N],double B[N][N],double C[N][N]);
