 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:  16
 
 
 
  *    STAGE Initialization and input   **
 
 
 
  ***   STAGE Linear dynamic analysis   **
 
  ****   STAGE Mass   assembly           **
 +===================+
 Total mass:  585000000000.0000
 +===================+
 
 
 
 :========================================:
 :**            END of FSTR             **:
 :========================================:
