MAKE = make

all: build-default

build-default:
	@cd neu2fstr   && $(MAKE) build-default

clean:
	@cd neu2fstr   && $(MAKE) clean

distclean:
	@cd neu2fstr   && $(MAKE) distclean

install:
	@cd neu2fstr   && $(MAKE) install
