MAKE = make

all: build-default

build-default:
	@cd hecmw                  && $(MAKE) build-default
	@cd visualizer             && $(MAKE) build-default

clean:
	@cd hecmw                  && $(MAKE) clean
	@cd visualizer             && $(MAKE) clean

distclean:
	@cd hecmw                  && $(MAKE) distclean
	@cd visualizer             && $(MAKE) distclean

install:
	@cd hecmw                  && $(MAKE) install
	@cd visualizer             && $(MAKE) install
