partition:
	../../ppohFEM/bin/ppohFEM_part 
run:
	mpirun -np 4 ../bin/app_heat
clean:
	rm -f MA361_vis_psf.0001.inp hecmw_part.log part.inp 0.log 1.log 2.log 3.log heat.dbg.0 heat.dbg.1 heat.dbg.2 heat.dbg.3 heat.msg heat.sta
