include ../../Makefile.in

all: build-default

build-default:
	@cd partitioner           && $(MAKE) build-default

clean:
	@cd partitioner           && $(MAKE) clean

distclean:
	@cd partitioner           && $(MAKE) distclean

install:
	@cd partitioner           && $(MAKE) install
