# Makefile for ppohVIS

default:
	(cd base ; make)
	(cd FDM3D ; make)

src:
	(cd base ; make)
	(cd FDM3D ; make)

clean:
	(cd base ; make clean)
	(cd FDM3D ; make clean)

distclean:
	(cd base ; make distclean)
	(cd FDM3D ; make distclean)

install:
	(cd base ; make install)
	(cd FDM3D ; make install)

uninstall:
	(cd base ; make uninstall)
	(cd FDM3D ; make uninstall)
